version: '3.9'

services:
  php-apache:
    image: php:8.3-apache
    container_name: php8-apache-symfony
    ports:
      - "8080:80"   # acessa em http://localhost:8080
    volumes:
      - .:/var/www/html
    environment:
     - APACHE_DOCUMENT_ROOT=/var/www/html/app/public # PATH public do Symfony(projeto)
    # instala extens√µes extras (opcional)
    user: "1000:1000"
    build:
      context: .
      dockerfile: dockerfile
    command: /bin/sh -c "sleep 2 && ./start.sh && apache2-foreground"
  